### ISSUE TITLE
No credentials for star schema lab

### ISSUE THREAD

**Issue by gopinaath007** [MicrosoftLearning/DP-500-Azure-Data-Analyst#1]
# Module: Understand scalability in Power BI
#### Step: 3 - Power BI setup

Description of issue

No credentials in https://microsoftlearning.github.io/DP-500-Azure-Data-Analyst/Instructions/labs/04-create-a-star-schema-model.html

Would be much easier if this lab could be launched in a sandbox vm to complete. too much configuration to do a star schema lab. 

Repro steps:

1. Go to https://microsoftlearning.github.io/DP-500-Azure-Data-Analyst/Instructions/labs/04-create-a-star-schema-model.html
 Look for lab sign-in for PowerBI

**Comment by shannonlindsay** [comment]
Hi @gopinaath007 - unfortunately this lab cannot be completed in the sandbox. We appreciate your feedback and will consider it moving forward.
