### ISSUE TITLE
Small typo in lab 01

### ISSUE THREAD

**Issue by Theelepel** [MicrosoftLearning/DP-500-Azure-Data-Analyst#2]
# Module: 01
#### Step: 05

Description of issue
Switch back to the Data page and use the ↻ button at the top right of Synapse Studio to refresh the page. Then view the Workspace tab in the Data pane, where a SQL database list is **no** displayed. Expand this list to verify that the Sales database has been created.

no == now

**Comment by shannonlindsay** [comment]
Thanks for catching this! The issue is fixed.
