### ISSUE TITLE
Context missing in Lab 01

### ISSUE THREAD

**Issue by Theelepel** [MicrosoftLearning/DP-500-Azure-Data-Analyst#4]
# Module: 01
## Lab/Demo: 01

Description of issue
It shows different ways to query the data. First using openrowset and then external data source and then external table. Maybe add a little bit of text on the differences? Or the _Why would you choose one over the other_?

For me it feels like it needs a bit of extra explaining.

**Comment by shannonlindsay** [comment]
Thanks for this feedback @Theelepel. I'm going to consider it - I'll leave the issue open until it's been addressed.

**Comment by Mihai-Ac** [comment]
Solved with PR #85
