### ISSUE TITLE
Lab 3: suspend/resume sql dedicated pool

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/DP-500-Azure-Data-Analyst#42]
# Module: 3
#### Step: 00

Description of issue: the setup.ps1 script will pause/suspend the dedicated pool at the end. While this is helping to save costs, it is annoying when learners start the actual exercise. One of the first tasks is to resume the dedicated pool and this potentially takes a few minutes again. Can we consider to not pause the dedicated pool in the setup script? (and add a disclaimer)

**Comment by weslbo** [comment]
FYI - here are some timings I've noticed:

- Creating the sql dedicated pool: 27 min
- Pausing the pool: 10 min
- Resuming the pool: 11 min

**Comment by shannonlindsay** [comment]
Wesley - unfortunately this isn't something we're able to change, as it's a cost control issue. We can talk more about it offline if you have any questions.  Thanks!
