### ISSUE TITLE
Lab 4: publish Power BI workspace in Synapse

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/DP-500-Azure-Data-Analyst#43]
# Module: 4 - Create a star schema model
#### Step: Select Publish if you are prompted.

Description of issue: when linking the Power BI workspace in Azure Synapse Analytics, there is no popup or anything asking to publish. Please add the steps required to Publish the changes to Azure Synapse Analytics

eg:
1. Navigate to Manage
2. Select Publish all

**Comment by markfitzqa** [comment]
Seems hit and miss whether the Power BI shows or not.  I usually have a SQL script and publish that, then refresh the synapse workspace at the browser level.

**Comment by shannonlindsay** [comment]
Thanks Wesley and Mark. I added a couple of steps to the end of the task. Please let me know if this doesn't solve the problem.
