### ISSUE TITLE
Lab 4 - DimProductSubcategory is not available in the DimProduct table

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/DP-500-Azure-Data-Analyst#44]
# Module: 4
#### Step: 31 - remove all columns

Description of issue: field DimProductSubcategory is not available in the DimProduct table. 

We have the DimProduct table (DirectQuery, not import) and should remove all columns except ProductKey, EnglishProductName, Color and DimProductSubcategory

The DimProductSubcategory is not available for selection. As a result, we cannot not expand the field.

![image](https://user-images.githubusercontent.com/53346841/188891575-8e377fd9-44ce-4b5d-967d-d8f6f90dc692.png)

**Comment by weslbo** [comment]
There are no relationships in the SQL Dedicated Pool, that's why Power BI Query Editor cannot show the additional columns and we cannot expand them. As a workaround we should include extra instructions to 

- bring in the DimProductSubcategory and DimProductCategory tables (directquery), 
- merge DimProductSubcategory with DimProductCategory
- Keep only the Name fields (EnglishProductSubcategoryName and EnglishProductCategoryName)
- merge DimProduct with this table

**Comment by shannonlindsay** [comment]
Thanks for pointing this out Wesley. I've added instructions for learners to merge in those detail columns, followed by disabling the load of the unnecessary dimensions.
