### ISSUE TITLE
Lab 9 - (Enforce model security) publish the report to which workspace?

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/DP-500-Azure-Data-Analyst#45]
# Module: 09
#### Step: 3

Description of issue:

Step 3 instructs us to: "In the Publish to Power BI window, select your workspace, and then select Select."
However, it is not clear WHICH workspace (My Workspace, or the Premium Workspace created earlier)

<img width="491" alt="image" src="https://user-images.githubusercontent.com/53346841/189312204-4ef4d81a-daaa-4686-bd99-1933c6412c3a.png">

Repro steps:

1.
1.
1.

**Comment by shannonlindsay** [comment]
Thanks for catching this Wesley - they should be publishing to the workspace they created in the "Create a Workspace" task. I've updated the instructions to reflect this.
