### ISSUE TITLE
Lab 9 - Salespeople_Australia security group does not exist

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/DP-500-Azure-Data-Analyst#46]
# Module: 9
#### Step: 5 In the Members box, commence entering Salespeople_Australia.

Description of issue

Salespeople_Australia security group does not exist

<img width="503" alt="image" src="https://user-images.githubusercontent.com/53346841/189314748-4c054970-325b-4917-8be8-8bf2539b74cd.png">

I like the note: "*Steps 5 through 8 are for demonstration purposes only, as they rely on the creation or existence of a Salespeople_Australia security group. If you have permissions and the knowledge to create security groups, please feel free to proceed.*"

But is should be more clear that no further action is necessary. 
Alternatively, can't we create the security group as part of the tenant provisioning?

**Comment by shannonlindsay** [comment]
Hi Wesley - unfortunately we can't create the security group, I tried and failed. I've amended the instructions to reflect that the Configure RLS section is optional. Please take a look and let me know your thoughts. Thank you!
