### ISSUE TITLE
Lab 10 - New-AzSqlDatabaseImport

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/DP-500-Azure-Data-Analyst#47]
# Module: 10
#### Step: 6

Description of issue

The script (setup2.ps1) will import the .bacpac file and wait for 5 minutes

```pwsh
New-AzSqlDatabaseImport -ResourceGroupName $ResourceGroupName -ServerName $ServerName -DatabaseName "AdventureWorksDW2022-DP500" -DatabaseMaxSizeBytes 5368709120  -StorageKeyType "StorageAccessKey" -StorageKey $(Get-AzStorageAccountKey -ResourceGroupName $ResourceGroupName -StorageAccountName $storageName).Value[0] -StorageUri "https://$($storageName).blob.core.windows.net/dp500/AdventureWorksDW2022-DP500.bacpac" -Edition "Standard" -ServiceObjectiveName "S2" -AdministratorLogin "sqladmin" -AdministratorLoginPassword $(ConvertTo-SecureString -String 'P@ssw0rd01' -AsPlainText -Force)

Start-Sleep -s 300
```
Potentially, the database import finishes earlier, or takes more than 5 minutes (leaving the learner to a state where the import has not finished)

<img width="923" alt="image" src="https://user-images.githubusercontent.com/53346841/189322501-e70a582e-ff14-46d9-b5cf-a77843178b59.png">

Can the script be updated to poll for the import/export status?  There is a command **Get-AzSqlDatabaseImportExportStatus**

More info https://docs.microsoft.com/en-us/powershell/module/az.sql/get-azsqldatabaseimportexportstatus?view=azps-8.3.0

**Comment by shannonlindsay** [comment]
I'm looking into this Wesley - thank you for investigating and proposing a solution!

**Comment by shannonlindsay** [comment]
Wesley - as an interim solution, we increased the time to sleep from 300 to 420 seconds.
