### ISSUE TITLE
Lab 10 - Missing instructions / TODO

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/DP-500-Azure-Data-Analyst#48]
# Module: 10
#### Step: 5, 6

Description of issue: there are some missing instructions found this task

<img width="301" alt="image" src="https://user-images.githubusercontent.com/53346841/189326377-ece542e7-5fe3-40b9-8e54-e5cae4febb97.png">

**Comment by AnthonyOakley** [comment]
I encountered the same issue.  I was able to input sqladmin and it's password to complete the step.  Screenshot could be added to Step 5 and Step 6 could be removed.

**Comment by shannonlindsay** [comment]
Thanks Wesley and Anthony! Noted and fixing ASAP!
