### ISSUE TITLE
Lab 10 - SSMS not able to connect to Azure SQL Database using AAD

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/DP-500-Azure-Data-Analyst#49]
# Module: 10
#### Step: 8

Description of issue: Not able to connect SSMS to Azure SQL Database using AAD-password

Cannot connect to dp500server-231363.database.windows.net.
AADSTS900021: Requested tenant identifier '00000000-0000-0000-0000-000000000000' is not valid. Tenant identifiers may not be an empty GUID.
Trace ID: 7a1279c8-9913-4828-b843-aaa5aa067500
Correlation ID: d2add445-8581-446e-afd9-1110b25ffefb
Timestamp: 2022-09-09 10:17:29Z (System.Data)

<img width="510" alt="image" src="https://user-images.githubusercontent.com/53346841/189328360-6e0f8a9f-01f5-4a4b-9e6b-58d5840af3bb.png">

It is possible to connect with the SQLADMIN account.

The solution to this is to change the instructions at step 6

<img width="299" alt="image" src="https://user-images.githubusercontent.com/53346841/189329261-175c16c7-5d8f-4ce2-a5e1-53549d0231a1.png">

**Comment by shannonlindsay** [comment]
Thanks Wesley and Anthony - this has been fixed!
