### ISSUE TITLE
the below code may potentially cause the registration running forever if the first registration cannot be finished within 3 seconds

### ISSUE THREAD

**Issue by KeeveySongMS** [MicrosoftLearning/DP-500-Azure-Data-Analyst#5]
The below code is in the step 5 https://microsoftlearning.github.io/DP-500-Azure-Data-Analyst/Instructions/labs/01-analyze-data-with-sql.html

but it may potentially cause the registration running forever if the first registration cannot be finished within 3 seconds

can you help verify so? Thank you very much

# Register resource providers
Write-Host "Registering resource providers...";
$provider_list = "Microsoft.Synapse", "Microsoft.Sql", "Microsoft.Storage", "Microsoft.Compute"
foreach ($provider in $provider_list){
    $result = Register-AzResourceProvider -ProviderNamespace $provider
    while ($result.RegistrationState -eq "Registering") {
        
        Start-Sleep -Seconds 3
        $result = Register-AzResourceProvider -ProviderNamespace $provider
    }
    Write-Host "$provider registered"
}

# Module: 00
#### Step: 00

Description of issue

Repro steps:

1.
1.
1.

**Comment by shannonlindsay** [comment]
@KeeveySongMS - I'll look into this and update the issue with my findings. Thanks for raising!

**Comment by weslbo** [comment]
I'm facing the same issue in lab 3 during the registration of the resource providers. https://github.com/MicrosoftLearning/DP-500-Azure-Data-Analyst/blob/main/Allfiles/03/setup.ps1

It keeps on running forever.

From the activity log, you can observe:

"Correlation id","Operation name","Status","Event category","Level","Time","Subscription","Event initiated by","Resource type","Resource group","Resource"
"27c0d2a5-cf70-49fc-98b4-83e2456dedf2","Registers the Azure Synapse Analytics (workspaces) Resource Provider.","Started","Administrative","Informational","2022-09-07T10:40:05.944Z","9f2bdec9-c15f-406c-ac9b-e011ed351ffc","User1-25527266@LODSPRODMSLEARNMCA.onmicrosoft.com","","","/subscriptions/9f2bdec9-c15f-406c-ac9b-e011ed351ffc/providers/Microsoft.Synapse"
"564a9442-54d2-4468-a51f-6ecfb73d633a","Registers the Azure Synapse Analytics (workspaces) Resource Provider.","Succeeded","Administrative","Informational","2022-09-07T10:39:58.831Z","9f2bdec9-c15f-406c-ac9b-e011ed351ffc","User1-25527266@LODSPRODMSLEARNMCA.onmicrosoft.com","","","/subscriptions/9f2bdec9-c15f-406c-ac9b-e011ed351ffc/providers/Microsoft.Synapse"
"564a9442-54d2-4468-a51f-6ecfb73d633a","Registers the Azure Synapse Analytics (workspaces) Resource Provider.","Started","Administrative","Informational","2022-09-07T10:39:57.189Z","9f2bdec9-c15f-406c-ac9b-e011ed351ffc","User1-25527266@LODSPRODMSLEARNMCA.onmicrosoft.com","","","/subscriptions/9f2bdec9-c15f-406c-ac9b-e011ed351ffc/providers/Microsoft.Synapse"
"564a9442-54d2-4468-a51f-6ecfb73d633a","Registers the Azure Synapse Analytics (workspaces) Resource Provider.","Started","Administrative","Informational","2022-09-07T10:39:57.189Z","9f2bdec9-c15f-406c-ac9b-e011ed351ffc","User1-25527266@LODSPRODMSLEARNMCA.onmicrosoft.com","","","/subscriptions/9f2bdec9-c15f-406c-ac9b-e011ed351ffc/providers/Microsoft.Synapse"
"564a9442-54d2-4468-a51f-6ecfb73d633a","Registers the Azure Synapse Analytics (workspaces) Resource Provider.","Succeeded","Administrative","Informational","2022-09-07T10:39:58.831Z","9f2bdec9-c15f-406c-ac9b-e011ed351ffc","User1-25527266@LODSPRODMSLEARNMCA.onmicrosoft.com","","","/subscriptions/9f2bdec9-c15f-406c-ac9b-e011ed351ffc/providers/Microsoft.Synapse"
"862cd10c-05b4-4400-8557-3893c7c1b463","Registers the Azure Synapse Analytics (workspaces) Resource Provider.","Succeeded","Administrative","Informational","2022-09-07T10:39:54.091Z","9f2bdec9-c15f-406c-ac9b-e011ed351ffc","User1-25527266@LODSPRODMSLEARNMCA.onmicrosoft.com","","","/subscriptions/9f2bdec9-c15f-406c-ac9b-e011ed351ffc/providers/Microsoft.Synapse"
"862cd10c-05b4-4400-8557-3893c7c1b463","Registers the Azure Synapse Analytics (workspaces) Resource Provider.","Started","Administrative","Informational","2022-09-07T10:39:52.560Z","9f2bdec9-c15f-406c-ac9b-e011ed351ffc","User1-25527266@LODSPRODMSLEARNMCA.onmicrosoft.com","","","/subscriptions/9f2bdec9-c15f-406c-ac9b-e011ed351ffc/providers/Microsoft.Synapse"
"862cd10c-05b4-4400-8557-3893c7c1b463","Registers the Azure Synapse Analytics (workspaces) Resource Provider.","Started","Administrative","Informational","2022-09-07T10:39:52.560Z","9f2bdec9-c15f-406c-ac9b-e011ed351ffc","User1-25527266@LODSPRODMSLEARNMCA.onmicrosoft.com","","","/subscriptions/9f2bdec9-c15f-406c-ac9b-e011ed351ffc/providers/Microsoft.Synapse"
"862cd10c-05b4-4400-8557-3893c7c1b463","Registers the Azure Synapse Analytics (workspaces) Resource Provider.","Succeeded","Administrative","Informational","2022-09-07T10:39:54.091Z","9f2bdec9-c15f-406c-ac9b-e011ed351ffc","User1-25527266@LODSPRODMSLEARNMCA.onmicrosoft.com","","","/subscriptions/9f2bdec9-c15f-406c-ac9b-e011ed351ffc/providers/Microsoft.Synapse"
"7905613b-b62d-4af4-bb2b-a48cfa9ecc42","Registers the Azure Synapse Analytics (workspaces) Resource Provider.","Succeeded","Administrative","Informational","2022-09-07T10:39:49.465Z","9f2bdec9-c15f-406c-ac9b-e011ed351ffc","User1-25527266@LODSPRODMSLEARNMCA.onmicrosoft.com","","","/subscriptions/9f2bdec9-c15f-406c-ac9b-e011ed351ffc/providers/Microsoft.Synapse"
"7905613b-b62d-4af4-bb2b-a48cfa9ecc42","Registers the Azure Synapse Analytics (workspaces) Resource Provider.","Started","Administrative","Informational","2022-09-07T10:39:47.855Z","9f2bdec9-c15f-406c-ac9b-e011ed351ffc","User1-25527266@LODSPRODMSLEARNMCA.onmicrosoft.com","","","/subscriptions/9f2bdec9-c15f-406c-ac9b-e011ed351ffc/providers/Microsoft.Synapse"
"068ac325-ffcf-41e8-a0b3-bf02ce61caf4","Registers the Azure Synapse Analytics (workspaces) Resource Provider.","Succeeded","Administrative","Informational","2022-09-07T10:39:44.752Z","9f2bdec9-c15f-406c-ac9b-e011ed351ffc","User1-25527266@LODSPRODMSLEARNMCA.onmicrosoft.com","","","/subscriptions/9f2bdec9-c15f-406c-ac9b-e011ed351ffc/providers/Microsoft.Synapse"
"068ac325-ffcf-41e8-a0b3-bf02ce61caf4","Registers the Azure Synapse Analytics (workspaces) Resource Provider.","Started","Administrative","Informational","2022-09-07T10:39:43.096Z","9f2bdec9-c15f-406c-ac9b-e011ed351ffc","User1-25527266@LODSPRODMSLEARNMCA.onmicrosoft.com","","","/subscriptions/9f2bdec9-c15f-406c-ac9b-e011ed351ffc/providers/Microsoft.Synapse"
"068ac325-ffcf-41e8-a0b3-bf02ce61caf4","Registers the Azure Synapse Analytics (workspaces) Resource Provider.","Started","Administrative","Informational","2022-09-07T10:39:43.096Z","9f2bdec9-c15f-406c-ac9b-e011ed351ffc","User1-25527266@LODSPRODMSLEARNMCA.onmicrosoft.com","","","/subscriptions/9f2bdec9-c15f-406c-ac9b-e011ed351ffc/providers/Microsoft.Synapse"
"068ac325-ffcf-41e8-a0b3-bf02ce61caf4","Registers the Azure Synapse Analytics (workspaces) Resource Provider.","Started","Administrative","Informational","2022-09-07T10:39:43.096Z","9f2bdec9-c15f-406c-ac9b-e011ed351ffc","User1-25527266@LODSPRODMSLEARNMCA.onmicrosoft.com","","","/subscriptions/9f2bdec9-c15f-406c-ac9b-e011ed351ffc/providers/Microsoft.Synapse"
"068ac325-ffcf-41e8-a0b3-bf02ce61caf4","Registers the Azure Synapse Analytics (workspaces) Resource Provider.","Succeeded","Administrative","Informational","2022-09-07T10:39:44.752Z","9f2bdec9-c15f-406c-ac9b-e011ed351ffc","User1-25527266@LODSPRODMSLEARNMCA.onmicrosoft.com","","","/subscriptions/9f2bdec9-c15f-406c-ac9b-e011ed351ffc/providers/Microsoft.Synapse"
"068ac325-ffcf-41e8-a0b3-bf02ce61caf4","Registers the Azure Synapse Analytics (workspaces) Resource Provider.","Succeeded","Administrative","Informational","2022-09-07T10:39:44.752Z","9f2bdec9-c15f-406c-ac9b-e011ed351ffc","User1-25527266@LODSPRODMSLEARNMCA.onmicrosoft.com","","","/subscriptions/9f2bdec9-c15f-406c-ac9b-e011ed351ffc/providers/Microsoft.Synapse"
"068ac325-ffcf-41e8-a0b3-bf02ce61caf4","Registers the Azure Synapse Analytics (workspaces) Resource Provider.","Succeeded","Administrative","Informational","2022-09-07T10:39:44.752Z","9f2bdec9-c15f-406c-ac9b-e011ed351ffc","User1-25527266@LODSPRODMSLEARNMCA.onmicrosoft.com","","","/subscriptions/9f2bdec9-c15f-406c-ac9b-e011ed351ffc/providers/Microsoft.Synapse"
"ae117314-ea0c-4dd7-aa83-e7dfdd241978","Registers the Azure Synapse Analytics (workspaces) Resource Provider.","Succeeded","Administrative","Informational","2022-09-07T10:39:32.373Z","9f2bdec9-c15f-406c-ac9b-e011ed351ffc","User1-25527266@LODSPRODMSLEARNMCA.onmicrosoft.com","","","/subscriptions/9f2bdec9-c15f-406c-ac9b-e011ed351ffc/providers/Microsoft.Synapse"

**Comment by weslbo** [comment]
When executing the statement manually, I get

```powershell
PS /home/user1-25527266/dp500/Allfiles/03> Register-AzResourceProvider -ProviderNamespace "Microsoft.Synapse"

ProviderNamespace : Microsoft.Synapse
RegistrationState : **Registering**
ResourceTypes     : {workspaces, workspaces/bigDataPools, workspaces/sqlPools, workspaces/sqlDatabases…}
Locations         : {West US 2, East US, North Europe, West Europe…}
```

**Comment by weslbo** [comment]
As a solution to fix the problem:

1. I first UNREGISTERED the Microsoft.Synapse resource provider. (This took some time)
2. Then registered it again using following command:

```powershell
Register-AzResourceProvider -ProviderNamespace "Microsoft.Synapse"
```

3. Then waited until it sucessfully finished registering:

```powershell
Get-AzResourceProvider -ListAvailable | Select-Object ProviderNamespace, RegistrationState | grep Synapse
Microsoft.Synapse                       Registering
Get-AzResourceProvider -ListAvailable | Select-Object ProviderNamespace, RegistrationState | grep Synapse
Microsoft.Synapse                       Registered
```

**Comment by weslbo** [comment]
So maybe the solution is to not keep registering the resource provider in the while-loop, but instead to get the RegistrationState and wait for it to be "registered"

```powershell
# Register resource providers
Write-Host "Registering resource providers...";
$provider_list = "Microsoft.Synapse", "Microsoft.Sql", "Microsoft.Storage", "Microsoft.Compute"
foreach ($provider in $provider_list){
    $result = Register-AzResourceProvider -ProviderNamespace $provider
    while ($result.RegistrationState -eq "Registering") {
        
        Start-Sleep -Seconds 3
        **$result = Register-AzResourceProvider -ProviderNamespace $provider**
    }
    Write-Host "$provider registered"
}
```

**Comment by shannonlindsay** [comment]
@weslbo - thanks for digging into this. I am going to consult with the team and will get back to this thread.

**Comment by shannonlindsay** [comment]
This issue has been rectified w PR #56.
