### ISSUE TITLE
Lab names in Skillable (LODS) not in sync with Lab titles

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/DP-500-Azure-Data-Analyst#53]
# Module: all
## Lab/Demo: all

Description of issue: The lab names as they appear in Skillable/LODS are not in sync. This makes it confusing to locate the correct lab (as they are also named different in the slides). 
For example: 

<img width="421" alt="image" src="https://user-images.githubusercontent.com/53346841/191037736-483dc90b-5a79-44cd-81ef-acad6a584a48.png">

**Comment by shannonlindsay** [comment]
Thanks for this Wesley! I am going to leave this issue open until I resolve it with Skillable. Thank you!

**Comment by markfitzqa** [comment]
Seems to be fixed now.

**Comment by shannonlindsay** [comment]
Thanks Mark! I worked with Skillable on this - glad to hear it's resolved.
