### ISSUE TITLE
Module 3 - Analyze data in a data lake with Spark wrong folder name when loading to dataframe

### ISSUE THREAD

**Issue by annav88** [MicrosoftLearning/DP-500-Azure-Data-Analyst#57]
# Lab title: Analyze data in a data lake with Spark
### Steps 3, 5, 7

Description of issue

The instruction is using an outdated snapshot Spark autogenerated code, where it points to a non-existing folder to load data to dataframe. The powerhsell script that does the configuration creates a different folder, and the instruction does not point to that new folder.

Repro steps:

Please see attached illustrations and update the instructions

**Comment by annav88** [comment]
![lab_03_ex_03](https://user-images.githubusercontent.com/83666021/197766156-9b82f85c-298a-4aaa-890a-076b71cacbf2.png)
![lab_03_ex_03_001](https://user-images.githubusercontent.com/83666021/197766161-83c9dce2-4576-4dd5-82c4-908ff92dd80a.png)

**Comment by GraemeMalcolm** [comment]
The folder in the source (where the setup script is run in the cloud shell) is called data. The script uploads the files in here to the /sales/orders folder in the data lake. The lab works as expected.
