### ISSUE TITLE
Lab 1 example queries missing wildcards at end of URL

### ISSUE THREAD

**Issue by dave-007** [MicrosoftLearning/DP-500-Azure-Data-Analyst#58]
# Lab title: Lab 1
### Step: 03

Description of issue
In the exercises like  'Use SQL to query parquet files', in step 3, the instructions example `OPENROWSET .. BULK` url lacks the `**` double wildcard suffix. 

This does match what the **New SQL Script**, **SELECT TOP 100 Rows** UI which does include the wildcards.

Other examples also lack the wildcard and confuse a student who might type in the query provided instead of generating the query using the UI.

![image](https://user-images.githubusercontent.com/240789/199618250-a21ff179-547d-4f12-87f4-857cdeb0c3f3.png)

**Comment by shannonlindsay** [comment]
Thanks @dave-007 - this has been updated.
