### ISSUE TITLE
DP-500-Azure-Data-Analyst/Instructions/labs/

### ISSUE THREAD

**Issue by pnk1119** [MicrosoftLearning/DP-500-Azure-Data-Analyst#59]
# Lab title: Query files using a serverless SQL pool
### Step:05

Description of issue :
The code is missing wildcard in BULK statement. Hence the query doesn't return what is mentioned in step # 06
SELECT YEAR(OrderDate) AS OrderYear,
       COUNT(*) AS OrderedItems
FROM
    OPENROWSET(
        BULK 'https://datalakexxxxxxx.dfs.core.windows.net/files/sales/parquet/',
        FORMAT = 'PARQUET'
    ) AS [result]
GROUP BY YEAR(OrderDate)
ORDER BY OrderYear

Repro steps:

1.
1.
1.

**Comment by shannonlindsay** [comment]
Thanks @pnk1119 - this has been resolved.
