### ISSUE TITLE
Module 1 - Lab 1 - Step 4 - BULK statement code stars should be removed

### ISSUE THREAD

**Issue by annav88** [MicrosoftLearning/DP-500-Azure-Data-Analyst#6]
# Module: 01
#### Step: 04

Description of issue

The code sample in the step 4 should not have the two star icons in the end of the BULK statement : 

-- This is auto-generated code
SELECT
    TOP 100 *
FROM
    OPENROWSET(
        BULK 'https://datalakexxxxxxx.dfs.core.windows.net/files/sales/csv**',
        FORMAT = 'CSV',
        PARSER_VERSION='2.0'
    ) AS [result]

Repro steps:

1. I launched Synapse workspace and executed the code
1. Got an error
1. Removed the two stars in BULK statement and it works

**Comment by shannonlindsay** [comment]
Thanks for raising this @annav88 - I'll take a look and close the issue once it's resolved!
