### ISSUE TITLE
Lab 13 Use tools to optimize Power BI performance

### ISSUE THREAD

**Issue by pnk1119** [MicrosoftLearning/DP-500-Azure-Data-Analyst#60]
# Lab title: Use tools to optimize Power BI performance
### Step: 02

Description of issue
The instruction says, "To load the BPA rules, select the Advanced Scripting tab" whereas, on the Tabular Editor, it's called "C# Scripting" and not "Advanced Scripting"

Repro steps:

1.
1.
1.

**Comment by shannonlindsay** [comment]
Thanks for pointing this out @pnk1119. The labs were created with an older version of Tabular Editor, which was labeled slightly differently. I've updated the instructions to reflect the changes in the latest version of Tabular Editor.
