### ISSUE TITLE
Lab 13 : Use tools to optimize Power BI performance

### ISSUE THREAD

**Issue by pnk1119** [MicrosoftLearning/DP-500-Azure-Data-Analyst#61]
# Lab title: Use tools to optimize Power BI performance
### Step: 13

Description of issue
The instruction says, "Switch to Tabular Editor, and select the Advanced Scripting tab" whereas, on the Tabular Editor, it's called "C# Scripting" and not "Advanced Scripting"

Repro steps:

1.
1.
1.

**Comment by shannonlindsay** [comment]
Duplicate issue with #60
