### ISSUE TITLE
Starter file (dataflow lab) contains reference to powerbi-sql machine, should be replaced with parameter

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/DP-500-Azure-Data-Analyst#63]
# Lab title: Create a dataflow
### Step: 4

Description of issue

Repro steps:

1. Open Sales Analysis - Create a dataflow.pbix
2. Open Power Query Editor, and notice that although a parameter has been defined for the SqlServerName, it's not used in any table. The powerbi-sql server name is still hard coded

**Comment by shannonlindsay** [comment]
Good catch Wesley. I'll get this updated and close the issue when it's finished. Thank you!

**Comment by shannonlindsay** [comment]
This has been updated. Thank you!
