### ISSUE TITLE
PowerBI login instructions

### ISSUE THREAD

**Issue by jleblancxaf** [MicrosoftLearning/DP-500-Azure-Data-Analyst#64]
# Lab title: 10
### Step: 1

Description of issue

Logging into Powerbi.com with lab credentials throws an error of UserNotLicensed.

Other labs describe logging into PowerBI Desktop first to enable the free trial. This method works, but is not present in lab 10 instructions.

![error](https://user-images.githubusercontent.com/110999055/207933653-b23053e1-526a-454e-9ded-7ba197399739.png)

**Comment by shannonlindsay** [comment]
Thanks for catching that the sign up is missing from the lab instructions @jleblancxaf. I'll take a look and close the issue once it's fixed.

**Comment by shannonlindsay** [comment]
This has been updated. Thanks!
