### ISSUE TITLE
Lab 16# PBI lenience issue

### ISSUE THREAD

**Issue by true-while** [MicrosoftLearning/DP-500-Azure-Data-Analyst#66]
# Lab title: 16

Description of issue

Before a user can sign in with a provided LOD account, the account should be activated. If the activation process is not completed it lead to the PBI portal hangs and errors "UserNoLicenced"

The workaround:
Activation of PBI by signing in from the PBI desktop app that forwards the user to the web page to provide email.

**Comment by shannonlindsay** [comment]
Thanks for the heads up - this has been fixed👍
