### ISSUE TITLE
Lab - Create a dataflow

### ISSUE THREAD

**Issue by chris-utter** [MicrosoftLearning/DP-500-Azure-Data-Analyst#67]
# Lab title: Create a dataflow
### Step: 08

The step does not instruct the student to choose (click) the Month Offset Filter Date dimension attribute, which in turn lights up the pop-up Column tools ribbon.

**Comment by shannonlindsay** [comment]
Hi @chris-utter - this is covered in step 7:

"To ensure the month offset filter values sort chronologically, in the Fields pane, select the Month Offset Filter field." 

Is there a different way you'd like this phrased to make it more clear? I'll leave the issue open until I hear back. Thanks!

**Comment by chris-utter** [comment]
That’s pretty clear to me Shannon, thank you

Chris Utter
Worldwide Learning
Microsoft
________________________________
