### ISSUE TITLE
Lab 5: Create a dataflow - "Get Data" not available

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/DP-500-Azure-Data-Analyst#68]
# Lab title: Create a dataflow
### Step: Create a dataflow

Description of issue:  The Get Data option is not available anymore in the Power BI Service UI.
![image](https://user-images.githubusercontent.com/53346841/213985342-5998e1c2-2ba0-45a3-9d8a-e68487a58323.png)

Suggested solution: Create the dataflow from within the workspace (choose **New**)

<img width="287" alt="image" src="https://user-images.githubusercontent.com/53346841/213985620-74cd5cc7-a129-473c-a0a5-07b64f7b588c.png">

**Comment by shannonlindsay** [comment]
Thanks Wesley! This is updated.
