### ISSUE TITLE
Lab #5 'sign in' to connect dataflow does not work from PBI desktop.

### ISSUE THREAD

**Issue by true-while** [MicrosoftLearning/DP-500-Azure-Data-Analyst#69]
# Lab 05
### Step: 4

Description of issue
several students completing Lab #5 find the following issue. "Sign in" button does not work properly and not allowed to connect with users account (cloud slice). 

Repro steps:
User clicking "Sign in" button and get error "We are Anable to connect..." like someone credentials already used for SSO. Meanwhile user already signed in Power BI with lab account. 

Workaround: 
The workaround I found is set default browser for sign in in the settings ("use my default web browser"). It helps to open browser and provide the user account explicitly.

**Comment by shannonlindsay** [comment]
@true-while - thanks for noting this. Tomorrow's update *should* eliminate this problem as we've updated the version of Power BI desktop. If it does not, I can add a note to the instructions to toggle that option on. Thanks for providing your feedback and improving the quality of the course!
