### ISSUE TITLE
Lab #10 no SQL user password provided

### ISSUE THREAD

**Issue by true-while** [MicrosoftLearning/DP-500-Azure-Data-Analyst#70]
# Lab: 10, Improve performance with hybrid tables

in the text of the LAB ask for connection as 'sqladmin' but no password provided.

password located in the script does not work.

**Comment by shannonlindsay** [comment]
Thanks for your review Mihai! I'm closing this issue as there hasn't been a reply. @true-while - please let us know if you're still experiencing difficulties.
