### ISSUE TITLE
DO500 Lab 10

### ISSUE THREAD

**Issue by markfitzqa** [MicrosoftLearning/DP-500-Azure-Data-Analyst#8]
# Module: 10-improve-performance-with-hybrid-tables.md
### Step: 8 - In the Current Value box, enter 6/1/2022 (June 1, 2022 - the VM uses US date formats).
Note that for non-MM-DD-YYYY format locations should be entered as 1/6/2022

# Module: 10-improve-performance-with-hybrid-tables.md
### Step: 10 - Set the following parameter properties:
Note that for non-MM-DD-YYYY format locations should be entered as 1/7/2022

# Module: 10-improve-performance-with-hybrid-tables.md
### Step: 3 - If necessary, in the Fiscal Year slicer, select the fiscal year that contains the current month (based on today's date).

The current month should be visible as a bar in the bar chart.

Note that Aug 2022 onwards which is not in the 2022 FY which is the default for the slicer.

# Module: 10-improve-performance-with-hybrid-tables.md
## Lab/Demo: dd an order to the database
The scripts in this module (InsertOrder.sql, 2. Cleanup.sql) both have the USE statement.  As this is an Azure Database the USE statement is not valid.  The user should connect to the adventureworksDP-500 database directly before executing.

**Comment by shannonlindsay** [comment]
Thanks Mark - I'll take a look at these today. I'll close the issue once all four issues are addressed.
