### ISSUE TITLE
Lab 12 starter pbix file has incorrect reference to xlsx file

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/DP-500-Azure-Data-Analyst#80]
# Lab title: (12) Improve query performance using aggregations
Description of issue: Lab 12 starter pbix file has incorrect reference to xlsx file

Repro steps:

- Open the following file: D:\DP500\Allfiles\12\Starter\Sales Analysis - Improve query performance with aggregations.pbix 
- Go to Power Query Editor (Transform Data)
- Notice the Targets table has an incorrect reference

![image](https://github.com/MicrosoftLearning/DP-500-Azure-Data-Analyst/assets/53346841/81a051eb-f87a-4091-bf82-6155b18e85ae)

- **Incorrect**: D:\DP500\Create a composite model\Assets\SalesTargets.xlsx
- **Correct**: D:\DP500\Allfiles\08\Assets\SalesTargets.xlsx

**Comment by weslbo** [comment]
The same is also true for Lab 11 (D:\DP500\Allfiles\11\Starter\Sales Analysis - Improve query performance with dual storage mode.pbix, which also points to the wrong xlsx file location

**Comment by shannonlindsay** [comment]
Files 11 & 12 are both updated. Thanks for catching this @weslbo!
