### ISSUE TITLE
Misleading reference to a "VM"

### ISSUE THREAD

**Issue by verargulla** [MicrosoftLearning/DP-500-Azure-Data-Analyst#81]
# Lab title: Create a star schema model
### Step: 01

The first step refers to a tab on "the right side of the VM". I'm completing this module as linked from this learning path: https://learn.microsoft.com/en-us/training/modules/understand-scalability-power-bi/4a-exercise-create-star-schema-model

I think the instructions on github is on the context of either the sandboxes which used to be provided or in an in-person training, neither of which is applicable to the self-paced module from DP-500.

This was the reason the DP-203 modules were so broken before. Can you please help fix and correct these references?

Thanks.

**Comment by shannonlindsay** [comment]
Hi @verargulla - thanks for raising this. I'll take a look and make the necessary adjustments. I'll close the issue when it's done!
