### ISSUE TITLE
Lab 10 - Date issue

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/DP-500-Azure-Data-Analyst#82]
# Lab title: Improve performance with hybrid tables
## Task: Set up incremental refresh

Description of issue

In the Adventureworks2020DW-500 SQL Database the last date key for the DimDate is the end of this month. So when we needed to calculate a due date for 10 days in the future in Lab 10, it violated the Data Integrity on the SQL server database. The fk between FactInternetSales and DimDate. The work around during the lab we used was changing the Due Date from (Today + 10 days) to (today + 2 days). But that won't work for next weeks deliveries. This resolved the issue this week however. We might need to add more recent Dates to DateDim in the Adventureworks202DW-500 Database. Perhaps an Insert script into DimDate as part of the scripts run during the lab might work?

**Comment by adamlimicrosoft** [comment]
@weslbo  Yes all learners are having this issue. I have raised a ticket to Skillable and hopefully they will fix the SQL script or modify the FK constraint.

**Comment by TheJamesHerring** [comment]
USE statement removed - also modified the dates to be within the DimDate table to no violate FK constraints (2). Also added step in notes to change the database context from `master` to `AdventureWorksDW2022-DP500` I will be testing again in AM but all ran find on this side.
