### ISSUE TITLE
labs\01-analyze-data-with-sql (column truncate)

### ISSUE THREAD

**Issue by sql-Agris** [MicrosoftLearning/DP-500-Azure-Data-Analyst#89]
# Lab title: labs\01-analyze-data-with-sql
## Task: Create an external table

Description of issue:
Sales/Json "Item" column has rows that are larger than varchar(30) which would lead to truncate error when querying the external table.

**Comment by shannonlindsay** [comment]
@AngieRudduck or @JulianePadrao - can you please assist and take a look when you get a moment? Thank you!
