### ISSUE TITLE
Lab 10: `1-InsertOrder.sql` query fails "Msg 40508" "USE statement is not supported"

### ISSUE THREAD

**Issue by SkillableMG** [MicrosoftLearning/DP-500-Azure-Data-Analyst#93]
- Lab 10: Improve performance with hybrid tables
- Exercise: Test the hybrid table
- Task: Add an order to the database
- step 10

Execution of the `1-InsertOrder.sql` query fails at the above-referenced step with the error message quoted below [f1].

```
Msg 40508, Level 16, State 1, Line 1
USE statement is not supported to switch between databases. Use a new connection to connect to a different database.
Msg 208, Level 16, State 1, Line 10
Invalid object name 'dbo.FactInternetSales'.
```

When connecting to the SQL server as specified by the instructions, the connection is made to the server master rather than to the AdventureWorksDW2022-DP500 database.

If the query is run in an connection to the AdventureWorksDW2022-DP500 database, the above error messages are not observed. Connecting to the database was tested via creating a new copy/pasted query from the Object Explorer, and via selecting the database on the Connection Properties tab of the Connect to Database Engine dialog (with Options expanded) when opening the query file. The result is the below set of messages which are consistent with the previous known behavior described under #83, #82 [f2].

```
Msg 547, Level 16, State 0, Line 12
The INSERT statement conflicted with the FOREIGN KEY constraint "FK_FactInternetSales_DimDate". The conflict occurred in database "AdventureWorksDW2022-DP500", table "dbo.DimDate", column 'DateKey'.
The statement has been terminated.
```

Potentially unnecessary for understanding this issue, but it was further confirmed that if the date issue is sidestepped by substituting an unaffected verbatim date for the `SYSDATETIME()` call, the query fully succeeds in adding the record [f3].

The same results were obtained in testing when following all labs steps and when following the minimal repro steps below.

Repro steps:

1. Complete tasks: 
    - Get started
        - Clone the repository for this course
        - Deploy an Azure SQL Database
        - Set up the Azure SQL Database
    - Test the hybrid table
        - Add an order to the database

[f1]
![image](https://github.com/MicrosoftLearning/DP-500-Azure-Data-Analyst/assets/134323425/e55c5972-db4c-4be9-bff0-830fa442cd69)

[f2]
![image](https://github.com/MicrosoftLearning/DP-500-Azure-Data-Analyst/assets/134323425/e10e0c12-a1a1-4e4f-a16d-afcf8e84aad1)

[f3]
![image](https://github.com/MicrosoftLearning/DP-500-Azure-Data-Analyst/assets/134323425/b9be0f35-ed9f-4089-9e4e-a9af5a704593)

**Comment by SkillableMG** [comment]
Thank you for the commits. Following the recent changes (diff below) the second error message from the original report is still encountered [f4].

https://github.com/MicrosoftLearning/DP-500-Azure-Data-Analyst/compare/6f348e6053e5445a2f44203364a9ec234c41a64a..229c204478d991b0011e4696c3ca2ac0ae3dad4c

```
Msg 208, Level 16, State 1, Line 7
Invalid object name 'dbo.FactInternetSales'
```

As in the original report, if the query is executed in a connection to the AdventureWorksDW2022-DP500 database rather than the server master, both error messages corresponding to this issue are avoided, and instead we fall through to the behavior noted in #83, #82 [f5].

The default database connection produced by the Connect to Database Engine window, when configured as specified by the instructions, is displayed as `dp500server-564241.database.windows.net.master` in the SSMS title bar. In the workaround case reflected in [f5], the connection is to `dp500server-564241.database.windows.net.AdventureWorksDW2022-DP500`. This different choice of database connection can be selected by choosing different options within the Connect to Database Engine window or by running a new query from the Object Explorer as in [f5].

[f4]
![Screenshot 2023-12-07 141447](https://github.com/MicrosoftLearning/DP-500-Azure-Data-Analyst/assets/134323425/3f4f9b25-a243-46ad-81bd-cd3de7c28a4b)

[f5]
![image](https://github.com/MicrosoftLearning/DP-500-Azure-Data-Analyst/assets/134323425/41002deb-d66d-4407-9e46-119a15a83477)

**Comment by JTomKinser** [comment]
The problem that I discovered is that the **Date** dimension table does not have dates after June 2023 so there's no Foreign Key equivalent to today's date. Either the **Date** table needs to be updated with dates for the rest of 2023 and 2024 for this lab to continue working **OR** instead of using today's date, add the following as the first line of the INSERT script to go back 1 year:         DECLARE @Today DATE = DATEADD(YEAR,-1, SYSDATETIME()) ;

**Comment by TheJamesHerring** [comment]
All of these issues have been resolved, but will be tested again in the AM @JTomKinser, thanks for patience and assistance on this matter. JH

**Comment by GraemeMalcolm** [comment]
[like]  Graeme Malcolm reacted to your message:
________________________________
