### ISSUE TITLE
Lab 07 - Lab Files cannot be downloaded

### ISSUE THREAD

**Issue by shielajchan** [MicrosoftLearning/DP-500-Azure-Data-Analyst#94]
# Lab title: Enhance a Report in Power BI Desktop
### Step: Download Files

Description of issue: 

Before starting the Labs, we have to copy the latest lab file from GitHub into the Lab virtual machine, apparently the lab files cannot be downloaded and having "Lab Files download failed. Please try again." error, even when closing and restarting the lab again, including restarting my Microsoft Learn session. 
![ErrorDownload](https://github.com/MicrosoftLearning/DP-500-Azure-Data-Analyst/assets/72311300/99cde346-9aa2-4eb1-ab4e-60b23c26a3c0)

**Comment by shannonlindsay** [comment]
@shielajchan - this is an issue with the Lab Hosting Provider. I will file a ticket with them.

**Comment by shielajchan** [comment]
> @shielajchan - this is an issue with the Lab Hosting Provider. I will file a ticket with them.
Thanks Shannon!
