### ISSUE TITLE
Unable to clone repo

### ISSUE THREAD

**Issue by Abhishek-Ramamurthy** [MicrosoftLearning/DP-500-Azure-Data-Analyst#98]
Instructions/labs/01-analyze-data-with-sql.md

Description of issue
Unable to clone the repo getting this error.

1.PS /home/abhi> rm -r dp500 -f                                                    
PS /home/abhi> git clone https://github.com/MicrosoftLearning/DP-500-Azure-Data-Analyst dp500
Cloning into 'dp500'...
remote: Enumerating objects: 1773, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (11/11), done.
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 7267 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
PS /home/abhi> 

Kindly help me

**Comment by shannonlindsay** [comment]
Update: 

This course will be retiring on 2024/4/30. Once the course is retired, all GitHub repos will be removed. 

As such, we will not be monitoring and fixing issues. Please be sure to clone or fork this repo if you'd like to retain the content.
